import type { CadFile } from "./cad-file-manager"

export const mockCadFiles: CadFile[] = [
  {
    id: "folder-1",
    name: "Rings",
    path: "/Rings",
    type: "folder",
    dateModified: "2023-05-15",
    modifiedBy: "Emma Johnson",
  },
  {
    id: "folder-2",
    name: "Necklaces",
    path: "/Necklaces",
    type: "folder",
    dateModified: "2023-05-10",
    modifiedBy: "Emma Johnson",
  },
  {
    id: "folder-3",
    name: "Earrings",
    path: "/Earrings",
    type: "folder",
    dateModified: "2023-05-12",
    modifiedBy: "Michael Chen",
  },
  {
    id: "folder-4",
    name: "Bracelets",
    path: "/Bracelets",
    type: "folder",
    dateModified: "2023-05-14",
    modifiedBy: "Sarah Williams",
  },
  {
    id: "folder-5",
    name: "Custom",
    path: "/Custom",
    type: "folder",
    dateModified: "2023-05-08",
    modifiedBy: "Emma Johnson",
  },
  {
    id: "folder-6",
    name: "Engagement",
    path: "/Rings/Engagement",
    type: "folder",
    dateModified: "2023-05-15",
    modifiedBy: "Emma Johnson",
  },
  {
    id: "folder-7",
    name: "Wedding",
    path: "/Rings/Wedding",
    type: "folder",
    dateModified: "2023-05-15",
    modifiedBy: "Emma Johnson",
  },
  {
    id: "file-1",
    name: "Diamond Solitaire.stl",
    path: "/Rings/Engagement/Diamond Solitaire.stl",
    type: "file",
    fileType: "stl",
    thumbnail: "/thumbnails/diamond-solitaire.png",
    dateModified: "2023-05-15",
    modifiedBy: "Emma Johnson",
    checkedOut: true,
    checkedOutBy: "Michael Chen",
    currentVersion: 3,
    versions: [
      {
        version: 1,
        date: "2023-05-01",
        author: "Emma Johnson",
        changes: "Initial design of diamond solitaire ring",
        approved: true,
        approvedBy: "Sarah Williams",
        approvedDate: "2023-05-02",
      },
      {
        version: 2,
        date: "2023-05-10",
        author: "Emma Johnson",
        changes: "Adjusted prong height and angle for better stone security",
        approved: true,
        approvedBy: "Sarah Williams",
        approvedDate: "2023-05-11",
      },
      {
        version: 3,
        date: "2023-05-15",
        author: "Emma Johnson",
        changes: "Added filigree detail to band sides",
        approved: false,
      },
    ],
    linkedWorkOrders: ["WO-2023-0125", "WO-2023-0142"],
  },
  {
    id: "file-2",
    name: "Emerald Cut Halo.stl",
    path: "/Rings/Engagement/Emerald Cut Halo.stl",
    type: "file",
    fileType: "stl",
    thumbnail: "/thumbnails/emerald-halo.png",
    dateModified: "2023-05-12",
    modifiedBy: "Michael Chen",
    currentVersion: 2,
    versions: [
      {
        version: 1,
        date: "2023-05-05",
        author: "Michael Chen",
        changes: "Initial design of emerald cut ring with halo setting",
        approved: true,
        approvedBy: "Sarah Williams",
        approvedDate: "2023-05-06",
      },
      {
        version: 2,
        date: "2023-05-12",
        author: "Michael Chen",
        changes: "Adjusted halo dimensions and added pave diamonds to band",
        approved: true,
        approvedBy: "Emma Johnson",
        approvedDate: "2023-05-13",
      },
    ],
    linkedWorkOrders: ["WO-2023-0136"],
  },
  {
    id: "file-3",
    name: "Twisted Band.stl",
    path: "/Rings/Wedding/Twisted Band.stl",
    type: "file",
    fileType: "stl",
    thumbnail: "/thumbnails/twisted-band.png",
    dateModified: "2023-05-08",
    modifiedBy: "Sarah Williams",
    currentVersion: 1,
    versions: [
      {
        version: 1,
        date: "2023-05-08",
        author: "Sarah Williams",
        changes: "Initial design of twisted band wedding ring",
        approved: true,
        approvedBy: "Emma Johnson",
        approvedDate: "2023-05-09",
      },
    ],
  },
  {
    id: "file-4",
    name: "Pendant Teardrop.glb",
    path: "/Necklaces/Pendant Teardrop.glb",
    type: "file",
    fileType: "glb",
    thumbnail: "/thumbnails/pendant-teardrop.png",
    dateModified: "2023-05-10",
    modifiedBy: "Emma Johnson",
    currentVersion: 2,
    versions: [
      {
        version: 1,
        date: "2023-05-03",
        author: "Emma Johnson",
        changes: "Initial design of teardrop pendant",
        approved: true,
        approvedBy: "Michael Chen",
        approvedDate: "2023-05-04",
      },
      {
        version: 2,
        date: "2023-05-10",
        author: "Emma Johnson",
        changes: "Added texture to pendant surface and adjusted bail size",
        approved: true,
        approvedBy: "Michael Chen",
        approvedDate: "2023-05-11",
      },
    ],
    linkedWorkOrders: ["WO-2023-0118"],
  },
  {
    id: "file-5",
    name: "Hoop Earrings.stl",
    path: "/Earrings/Hoop Earrings.stl",
    type: "file",
    fileType: "stl",
    thumbnail: "/thumbnails/hoop-earrings.png",
    dateModified: "2023-05-12",
    modifiedBy: "Michael Chen",
    currentVersion: 1,
    versions: [
      {
        version: 1,
        date: "2023-05-12",
        author: "Michael Chen",
        changes: "Initial design of classic hoop earrings",
        approved: false,
      },
    ],
  },
  {
    id: "file-6",
    name: "Tennis Bracelet.stl",
    path: "/Bracelets/Tennis Bracelet.stl",
    type: "file",
    fileType: "stl",
    thumbnail: "/thumbnails/tennis-bracelet.png",
    dateModified: "2023-05-14",
    modifiedBy: "Sarah Williams",
    currentVersion: 3,
    versions: [
      {
        version: 1,
        date: "2023-04-28",
        author: "Sarah Williams",
        changes: "Initial design of tennis bracelet",
        approved: true,
        approvedBy: "Emma Johnson",
        approvedDate: "2023-04-29",
      },
      {
        version: 2,
        date: "2023-05-05",
        author: "Sarah Williams",
        changes: "Adjusted link connections for better flexibility",
        approved: true,
        approvedBy: "Emma Johnson",
        approvedDate: "2023-05-06",
      },
      {
        version: 3,
        date: "2023-05-14",
        author: "Sarah Williams",
        changes: "Modified clasp design for improved security",
        approved: true,
        approvedBy: "Michael Chen",
        approvedDate: "2023-05-15",
      },
    ],
    linkedWorkOrders: ["WO-2023-0130", "WO-2023-0145"],
  },
  {
    id: "file-7",
    name: "Custom Monogram Pendant.glb",
    path: "/Custom/Custom Monogram Pendant.glb",
    type: "file",
    fileType: "glb",
    thumbnail: "/thumbnails/monogram-pendant.png",
    dateModified: "2023-05-08",
    modifiedBy: "Emma Johnson",
    currentVersion: 1,
    versions: [
      {
        version: 1,
        date: "2023-05-08",
        author: "Emma Johnson",
        changes: "Custom monogram pendant for client J.S.",
        approved: true,
        approvedBy: "Sarah Williams",
        approvedDate: "2023-05-09",
      },
    ],
    linkedWorkOrders: ["WO-2023-0139"],
  },
]

export const mockWorkOrders = [
  {
    id: "WO-2023-0118",
    customer: "Rebecca Martinez",
    description: "Teardrop Pendant in 18K Gold",
    dueDate: "2023-06-15",
    status: "In Progress",
    type: "Custom Order",
  },
  {
    id: "WO-2023-0125",
    customer: "Jennifer Adams",
    description: "Diamond Solitaire Engagement Ring",
    dueDate: "2023-06-10",
    status: "In Progress",
    type: "Engagement Ring",
  },
  {
    id: "WO-2023-0130",
    customer: "Patricia Johnson",
    description: "Diamond Tennis Bracelet in White Gold",
    dueDate: "2023-06-20",
    status: "Pending Materials",
    type: "Custom Order",
  },
  {
    id: "WO-2023-0136",
    customer: "Thomas Wilson",
    description: "Emerald Cut Engagement Ring with Halo",
    dueDate: "2023-06-25",
    status: "In Progress",
    type: "Engagement Ring",
  },
  {
    id: "WO-2023-0139",
    customer: "James Smith",
    description: "Custom Monogram Pendant in Rose Gold",
    dueDate: "2023-06-18",
    status: "Completed",
    type: "Custom Order",
  },
  {
    id: "WO-2023-0142",
    customer: "Emily Davis",
    description: "Diamond Solitaire Ring Resize",
    dueDate: "2023-06-05",
    status: "In Progress",
    type: "Repair",
  },
  {
    id: "WO-2023-0145",
    customer: "Michael Brown",
    description: "Tennis Bracelet Clasp Repair",
    dueDate: "2023-06-08",
    status: "Waiting for Approval",
    type: "Repair",
  },
  {
    id: "WO-2023-0148",
    customer: "Sarah Johnson",
    description: "Custom Wedding Band Set",
    dueDate: "2023-07-10",
    status: "Not Started",
    type: "Wedding Rings",
  },
  {
    id: "WO-2023-0152",
    customer: "David Miller",
    description: "Sapphire and Diamond Pendant",
    dueDate: "2023-07-05",
    status: "Not Started",
    type: "Custom Order",
  },
  {
    id: "WO-2023-0155",
    customer: "Lisa Garcia",
    description: "Pearl Earrings Repair",
    dueDate: "2023-06-12",
    status: "In Progress",
    type: "Repair",
  },
]
