-- 🚨 TEMPORARILY DISABLE RLS FOR TESTING
-- ⚠️  WARNING: This removes security - ONLY USE FOR TESTING!
-- 🗑️  REMEMBER TO RE-ENABLE AFTER TESTING!

-- Disable RLS on team tables temporarily
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_invitations DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_performance_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_activity_logs DISABLE ROW LEVEL SECURITY;

-- Verify RLS is disabled
DO $$
BEGIN
    RAISE NOTICE '🔓 RLS temporarily disabled for testing';
    RAISE NOTICE '⚠️  REMEMBER TO RE-ENABLE AFTER TESTING!';
    RAISE NOTICE '';
    RAISE NOTICE 'To re-enable RLS later, run:';
    RAISE NOTICE 'ALTER TABLE teams ENABLE ROW LEVEL SECURITY;';
    RAISE NOTICE 'ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;';
    RAISE NOTICE 'ALTER TABLE team_invitations ENABLE ROW LEVEL SECURITY;';
    RAISE NOTICE 'ALTER TABLE team_projects ENABLE ROW LEVEL SECURITY;';
    RAISE NOTICE 'ALTER TABLE project_members ENABLE ROW LEVEL SECURITY;';
    RAISE NOTICE 'ALTER TABLE team_performance_metrics ENABLE ROW LEVEL SECURITY;';
    RAISE NOTICE 'ALTER TABLE team_activity_logs ENABLE ROW LEVEL SECURITY;';
END $$;
